site_name: Cisco DC PoV Lab

nav:
    - Home: index.md
    - ACI自动化上线:
        - 背景信息: ztp/index.md
        - 实验拓扑: ztp/ztp-topo.md
        - 注意事项: ztp/ztp-note.md
        - 场景演示: ztp/ztp-scenario.md
    #- ACI BareMetal服务器接入: baremetal/index.md
    #- ACI VMWare VMM集成: vmware/index.md
    #- ACI L3out: l3out/index.md
    #- ACI高效运维: operation/index.md
    #- ACI自动化: automation/index.md
    #- ACI Netflow: netflow/index.md
    #- ACI Red Hat VMM集成:
    #    - 背景信息: rhv/rhv-index.md
    #    - 实验拓扑: rhv/rhv-topo.md
    - ACI K8s集成:
        - 背景信息: k8s/index.md
        - 集成前准备: k8s/k8s-prerequisite.md
        - K8s安装: k8s/k8s-installation.md
        - ACI CNI集成: k8s/k8s-cni.md
        - 部署容器应用: k8s/k8s-guestbook.md
        - K8s排错: k8s/k8s-troubleshooting.md
    - ACI CCP集成:
        - 背景信息: ccp/index.md
        - 集成前准备: ccp/ccp-prerequisite.md
        - CCP安装: ccp/ccp-installation.md
        - CCP V2 Cluster 设置: ccp/ccp-v2-setup.md
        - CCP V3 Cluster 设置: ccp/ccp-v3-setup.md
        - CCP Calico Cluster 设置: ccp/ccp-calico-setup.md
        - 部署容器应用: ccp/ccp-guestbook.md
        - CCP排障: ccp/ccp-troubleshooting.md
    - DCNM 安装部署:
        - 背景信息: dcnm/index.md
        - DCNM安装: dcnm/dcnm-install.md
        - DCNM配置: dcnm/dcnm-setup.md
        - DCNM运维: dcnm/dcnm-operation.md
        - 部署Nexus Insights: dcnm/dcnm-ni.md
        - 排错: dcnm/dcnm-troubleshooting.md

theme: readthedocs
